version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: 'clientdb'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - "3306:3306"
    volumes:
      - my-db:/var/lib/mysql
    networks:
      - adminer-network

  adminer:
    image: adminer
    restart: always
    ports:
      - "8090:8090"
    networks:
      - adminer-network

volumes:
  my-db:

networks:
  adminer-network: